import { Product } from "@/types";
import { v4 as uuidv4 } from "uuid";

export const carts = [
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-1.png",
    brand: "1",
    category: "1",
    origin: "1",
  },
];

export const initialProducts: Product[] = [
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-1.png",
    brand: "1",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-2.png",
    brand: "1",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-3.png",
    brand: "1",
    category: "2",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "3",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "3",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "2",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-1.png",
    brand: "1",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-2.png",
    brand: "1",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-3.png",
    brand: "1",
    category: "2",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "3",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "3",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "2",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-1.png",
    brand: "1",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-2.png",
    brand: "1",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-3.png",
    brand: "1",
    category: "2",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "3",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "3",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "2",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-1.png",
    brand: "1",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-2.png",
    brand: "1",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-3.png",
    brand: "1",
    category: "2",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "3",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "3",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "2",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-1.png",
    brand: "1",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-2.png",
    brand: "1",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-3.png",
    brand: "1",
    category: "2",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "3",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "3",
    category: "1",
    origin: "1",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "2",
  },
];

export const fetchData = (page: number, limit: number) => {
  const start = page * limit - limit;
  const end = page * limit;
  const data = initialProducts.slice(start, end);
  return {
    data: data || [],
    total: initialProducts.length,
    currentPage: page,
    limit,
    hasMore: data?.length > 0,
  };
};
