import { Product } from "@/types";
import { v4 as uuidv4 } from "uuid";

export const carts = [
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-1.png",
    brand: "1",
    category: "1",
    origin: "1",
    classification: "engine",
  },
];

export const classificationList = [
  { id: "engine", name: "Engine" },
  { id: "body", name: "Body" },
  { id: "electrical", name: "Electrical" },
  { id: "interior", name: "Interior" },
  { id: "exterior", name: "Exterior" },
  { id: "suspension", name: "Suspension" },
  { id: "brakes", name: "Brakes" },
  { id: "cooling", name: "Cooling" },
  { id: "transmission", name: "Transmission" },
  { id: "fuel", name: "Fuel" },
  { id: "lighting", name: "Lighting" },
  { id: "wheels", name: "Wheels" },
  { id: "tires", name: "Tires" },
  { id: "accessories", name: "Accessories" },
];

export const initialProducts: Product[] = [
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-1.png",
    brand: "1",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-2.png",
    brand: "1",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-3.png",
    brand: "1",
    category: "2",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "3",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "3",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "2",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-1.png",
    brand: "1",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-2.png",
    brand: "1",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-3.png",
    brand: "1",
    category: "2",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "3",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "3",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "2",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-1.png",
    brand: "1",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-2.png",
    brand: "1",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-3.png",
    brand: "1",
    category: "2",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "3",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "3",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "2",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-1.png",
    brand: "1",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-2.png",
    brand: "1",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-3.png",
    brand: "1",
    category: "2",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "3",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "3",
    category: "1",
    origin: "1",
    classification: "engine",
  },
  {
    id: uuidv4(),
    name: "Lọc gió động cơ Air Filter - Chevrolet Colorado, Trail...",
    price: 299000,
    originalPrice: 329000,
    image: "/images/air-filter-4.png",
    brand: "1",
    category: "1",
    origin: "2",
    classification: "engine",
  },
];

export const fetchData = (page: number, limit: number) => {
  const start = page * limit - limit;
  const end = page * limit;
  const data = initialProducts.slice(start, end);
  return {
    data: data || [],
    total: initialProducts.length,
    currentPage: page,
    limit,
    hasMore: data?.length > 0,
  };
};

export const fetchDataByClassification = (
  classification: string,
  page: number,
  limit: number
) => {
  const filtered = initialProducts.filter(
    (product) => product.classification === classification
  );
  const start = page * limit - limit;
  const end = page * limit;
  const data = filtered.slice(start, end);
  return {
    data: data || [],
    total: filtered.length,
    currentPage: page,
    limit,
    hasMore: data?.length > 0,
  };
};

export const fetchClassifications = (page = 1, limit = 10) => {
  const start = page * limit - limit;
  const end = page * limit;
  const data = classificationList.slice(start, end);
  return {
    data: data || [],
    total: classificationList.length,
    currentPage: page,
    limit,
    hasMore: data?.length > 0,
  };
};
